-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 18:47:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dojos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dojos` ;

-- -----------------------------------------------------
-- Schema dojos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dojos` DEFAULT CHARACTER SET utf8 ;
USE `dojos` ;

-- -----------------------------------------------------
-- Table `dojos`.`ninjas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dojos`.`ninjas` ;

CREATE TABLE IF NOT EXISTS `dojos`.`ninjas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `dojo` VARCHAR(45) NULL,
  `date_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_updated` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `dojo_id` INT NULL,
  PRIMARY KEY (`id`, `date_created`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `dojos`.`dojos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dojos`.`dojos` ;

CREATE TABLE IF NOT EXISTS `dojos`.`dojos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `date_created` DATETIME NULL DEFAULT NOW(),
  `date_updated` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `ninjas_id` INT NOT NULL,
  `ninjas_date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dojos_ninjas_idx` (`ninjas_id` ASC, `ninjas_date_created` ASC) VISIBLE,
  CONSTRAINT `fk_dojos_ninjas`
    FOREIGN KEY (`ninjas_id` , `ninjas_date_created`)
    REFERENCES `dojos`.`ninjas` (`id` , `date_created`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
